language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
- ./ci/benchmark.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "gQ8xdHkNNUzy/4zwMwjhj15XSHP2kuvPMRDru89Rfk7LMHqWIBohrPzMnupa0AoP7TFSVj9+4+pVFp2kN6lhoYUsoJOldz31zwntjkifUQoYEy2b3ZZ390hjB9PN22PuusL5LwTe0CtYNzpDBNr/3uRq+s/P/W+Cp7B3v6UUv2BfpRN27uoS2D06mghYr3pS6TNMfrjUQEylZN8bbZYitH/ePHPUZ29AdJyjLe8fsFo6/jhyGzTviVPyPoi+k79/zn3K717aAqqMwMiptTVgzvwzgRUh+ebi0raJOR4fqJBVZ2B1jkUuHYMypVNovdOwDhiqXBI8ABOjk9O4ToAkjo1gyfv0aUxQGgrzVqC8H2pXPy9zyRBbJyh69O3psZohh0fZrWPwvMCSZv9/A+fNWAo1Mz5eW/p4hOzV/SQF7Rzm85S8ovZJdH/oeauFx+7MXW6Zaw+0X7lstHyJFvqRfKjeoRnqh/0m97a9gmWlZLV1IWhvhifzy5aBUCGADBx3u9Ip3ZpmV0upFmWRzXCEpHSgIDkq4l84Huq/fUUVRPxpBdaJZdgoETa22vfca1i8DzjA/+5vGj+CluXpVJRjwgvreQbTWmGgRBjfmeS8/pMHm21Bgd3e4ghQN0ayPXLikvdiyBFlj4ExXhFH65lhAfEBTAwn4yrbwP0gi4nBAcI="
